[General]
Clipboard=ask
DashSupported=true
Language=auto
LastFormat=0
MainTab=1
Notifications=finish
ProxyAuthenticationRequired=false
ProxyHost=
ProxyPassword=
ProxyPort=0
ProxyType=0
ProxyUsername=
UseProxy=false
facebookRememberLogin=true
ffmpegPath=ffmpeg
firstStarted=2019-10-13 11:58:43.03726400
rememberLogins=true
rememberVideoQuality=true
saveLastPath=true
savedPath=/home/afropunk/Desktop
vimeoRememberLogin=true
youtubeRememberLogin=true
