[General]
key_pmi=8095526488
key_pmi_invite_msg="David Robert Lewis is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: David Robert Lewis' Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://us04web.zoom.us/j/8095526488?pwd=U2tXSENVMUg4VHdGdm9hOUxyc1UyQT09\r\n\r\nMeeting ID: 809 552 6488\r\nPasscode: 5chBdL\r\n\r\n"
