[General]
Geometry-MainForm=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\x9d\0\0\0\xa4\0\0\x4-\0\0\x2\x82\0\0\x1\x9d\0\0\0\xc9\0\0\x4-\0\0\x2\x82\0\0\0\0\0\0\0\0\a\x80)
Geometry-ToolBars=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x2\x91\0\0\x1\x38\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x4\0\0\0\x16\0m\0\x61\0i\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x16\0\x65\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\xfc\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x16\0v\0i\0\x65\0w\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x1\x9a\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x16\0\x66\0i\0n\0\x64\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x1\xd8\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x5\0\0\0\x18\0t\0o\0o\0l\0s\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x18\0\x66\0o\0r\0m\0s\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\xf7\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0o\0\x62\0j\0\x65\0\x63\0t\0s\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x1\xd7\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1e\0\x63\0o\0m\0m\0\x65\0n\0t\0s\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x2\x15\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0 \0r\0\x65\0\x64\0\x61\0\x63\0t\0i\0o\0n\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\x2S\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
ID=00000031-0032-0037-3337-333534373331
ImportFilePath=/home/afropunk/Documents
IsMaximized-MainForm=false
Show%20Forms_Tool_Bar=true
Show%20Statusbar=true
Show-Comments_Tool_Bar=true
Show-Edit_Tool_Bar=true
Show-Find_Tool_Bar=true
Show-Main_Tool_Bar=true
Show-Tools_Tool_Bar=true
Show-View_Tool_Bar=true
SidebarUrls=@Invalid()
antialiasing_image=true
antialiasing_path=true
antialiasing_text=true
change_font=true
check_updates=1
close_app_normal=true
create_backup_file=true
default%20PageLayout=0
default%20PageZoom=3
default_font=Helvetica
default_font_color=0
default_font_size=12
destination_save_as=0
enable_javascript=true
enable_scroll_wheel_zooming=true
highlight_form_color=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xe0\xe0\xf\xf\0\0)
highlight_required_form_color=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)
last_check_update=1574930243
last_editing_tool=4
main-version=5322
mouse_move_time=200
openFilePath=/home/afropunk/Documents/Mohope
open_doc_twice=false
open_one_window=true
page_background_color=@Variant(\0\0\0\x43\x1\xff\xff\x80\x80\x80\x80\x80\x80\0\0)
page_text_color=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
replace_doc_color=false
resolution_dpi=0
restore_last_session_application=false
restore_last_session_files=false
rightTabSize=136
saveFilePath=/home/afropunk/Documents/Mohope
selected_item_hover_mouse=false
show%20FormWidget=true
show%20MediaBox=false
show%20ObjectInspector=true
show_console_javascript=false
show_icons=false
snap_to_grid=false
str_destination_save_as=/home/afropunk/Documents
view_grid=false

[DistanceTool]
units=pt
units_1=pt
value=1
value_1=1

[resent_files_history]
1\fileName=/home/afropunk/Documents/Mohope/Business Card2.pdf
1\is_CoverFacingPages=false
1\is_FacingPages=false
1\is_FitPage=false
1\is_FitWidth=true
1\leftPanelIndex=0
1\leftPanelSize=29
1\rightPanelSize=136
1\top=0
1\zoom=176.94704049844236
2\fileName=/home/afropunk/Documents/Mohope/Business Card.pdf
2\is_CoverFacingPages=false
2\is_FacingPages=false
2\is_FitPage=false
2\is_FitWidth=true
2\leftPanelIndex=0
2\leftPanelSize=29
2\rightPanelSize=29
2\top=0
2\zoom=221.3914794921875
size=2
