[[item]]
file = '~/.themes/FlatColor/colors3'
template = 'gtk-flatcolor'
subtemplate = 'gtk-3'
rewrite = true
hook = 'systemctl restart --user xsettingsd &'

[[item]]
file = '~/.themes/FlatColor/colors2'
template = 'gtk-flatcolor'
subtemplate = 'gtk-2'
rewrite = true
hook = 'gtkrc-reload &'
